[package]
name = "pef"
version = "0.1.0"
authors = ["lightjacket <https://github.com/lightjacket>"]
edition = "2018"
license = "MIT"
description = ""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
flate2 = "1.0"
